# Generated by Django 5.1.7 on 2026-04-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.CharField(max_length=100)),
                ('loc', models.TextField()),
                ('inv', models.CharField(choices=[('Structural', 'Structural'), ('Non-Structural', 'Non-Structural'), ('Vehicular', 'Vehicular')], max_length=20)),
                ('occ', models.CharField(max_length=200)),
                ('dmg_raw', models.BigIntegerField(default=0)),
                ('alarm', models.CharField(choices=[('1st Alarm', '1st Alarm'), ('2nd Alarm', '2nd Alarm'), ('3rd Alarm', '3rd Alarm'), ('4th Alarm', '4th Alarm'), ('5th Alarm', '5th Alarm'), ('EUA', 'EUA'), ('FOA', 'FOA'), ('FOUA', 'FOUA'), ('N/A', 'N/A')], max_length=20)),
                ('sta', models.CharField(max_length=100)),
                ('eng', models.CharField(max_length=100)),
                ('by_user', models.CharField(max_length=200)),
                ('inj_c', models.IntegerField(default=0)),
                ('inj_b', models.IntegerField(default=0)),
                ('cas_c', models.IntegerField(default=0)),
                ('cas_b', models.IntegerField(default=0)),
                ('rem', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
